feat: Add environment to application
meroxa/meroxa-go pull request #157
Opened 2023-01-26 19:03 UTC by raulb

Fixes https://github.com/meroxa/meroxa-go/issues/153.

Part of the addition of Environments to Turbine applications.

This will be fully tested in the CLI (currently in progress)

2023-01-26 19:23 UTC, anna-cross approved these changes

2023-01-27 00:28 UTC, anna-cross requested changes
Actually, could we add Environment info to CreateApplicationInput like we did for CreateResourceInput ?

2023-01-27 09:22 UTC, raulb commented
@anna-cross I don't think that's necessary ([see slack](https://meroxa.slack.com/archives/C03F15EKFU3/p1674809505292129?thread_ts=1674767403.178829&cid=C03F15EKFU3)). Let me know if you think I'm missing something.

2023-01-27 14:51 UTC, raulb commented
@anna-cross Ignore me. I just went through the flow, and I think at the moment it makes sense to create the application with the environment information already. I'll make that change.

2023-01-27 16:28 UTC, anna-cross approved these changes

2023-01-30 12:36 UTC, merged